services:
    Uerka\TranslationFormBundle\Form\Type\TranslationsType:
        class: Uerka\TranslationFormBundle\Form\Type\TranslationsType
        arguments: 
            - []
        tags:
            - { name: form.type }